### ISSUE TITLE
Switching Between Historical Data Breaks Display Info  

### ISSUE THREAD

**Issue by ciacci1234** [Anti-Gerrymandering/visualization#27]
Perhaps this is related to caching issue @jonmast mentioned?

Here is a small video of the problem. I didn't notice any errors logged in the console or anything.

http://recordit.co/u849MKALXz

**Comment by ciacci1234** [comment]
Found an error associated with issue 👌 

![historicaldataerror](https://cloud.githubusercontent.com/assets/14255433/25416230/bc2cb80a-2a0a-11e7-8d8e-520a958bd9ba.png)

**Comment by jonmast** [comment]
The issue seems to be that the AFFGEOIDs change every year ☹️ The AFFGEOIDs in the stats are only valid for 2015, so stats will only appear for that year.

@aaronclong Any suggestions on an alternate identifier we could use? Perhaps "$branch_$district_number" (eg: "federal_7")?

**Comment by ciacci1234** [comment]
@jonmast So whatever identifier is used needs to be consistent throughout the json files? I noticed the "CD114FP" key which may be useful?

**Comment by jonmast** [comment]
@ciacci1234 It appears that the US House shapefile uses CD114FP for the district number, but the state level uses "Name" instead. Whatever key we use needs to be consistent for a district across multiple years, and would preferably be unique across offices as well.

**Comment by ciacci1234** [comment]
Hmm, sorry, but I'm having trouble understanding, could you explain to me why a district's ID requires consistency across multiple years? When a user requests a certain year, doesn't Leaflet just have to draw a map based on that year's geojson file?

**Comment by jonmast** [comment]
@ciacci1234 The reason they need to be consistent across years is so that we can match them with the appropriate stats. This is the only problem with AFFGEOID, and is what is causing our bug.

**Comment by aaronclong** [comment]
Sorry I just saw this thread.
I was talking to a few people and they suggested breaking the map down into particularly important years and not every year.
We are just adding a lot of complexity to our app with little pay off. 
I don't know how to resolve a unique primary key with our AFFGEOID, we could come up with our own convention to manage this. However, we would need Lauren's input to make an educated decision on this.
Potentially it might be easier to manage this with a back-end system?
The app is modular enough that we could start writing a backend and just have endpoints spitting out JSON.
@jonmast @ciacci1234

**Comment by jonmast** [comment]
@aaronclong 
> I was talking to a few people and they suggested breaking the map down into particularly important years and not every year.
We are just adding a lot of complexity to our app with little pay off.

I don't see how only doing "important" years will reduce complexity for our app. I agree it would be a good idea from UX standpoint, but I don't think it will help with our issue here.

> I don't know how to resolve a unique primary key with our AFFGEOID, we could come up with our own convention to manage this. However, we would need Lauren's input to make an educated decision on this.

I'm not sure I follow what you are getting at here. While it would be nice to use an existing ID system for compatibility, none of them seem to satisfy our precise needs, so I think we need something custom. This will be strictly internal so it shouldn't really matter what we use as long as we are consistent. I've opened a PR (#32) with a simple example of this, let me know if you have a better idea.

> Potentially it might be easier to manage this with a back-end system?
The app is modular enough that we could start writing a backend and just have endpoints spitting out JSON.

Having a back-end system could help centralize this type of thing, but I don't see a compelling reason to go there at this point. Could you elaborate on exactly what you would envision the backend doing?
